### ISSUE TITLE
Unable to successfully complete onboarding

### ISSUE THREAD

**Issue by thesurlydev** [KittyCAD/documentation#100]
I attempted to go through the onboarding process documented here: https://kittycad.io/docs/tutorials/onboarding. I wasn't able to complete it. 

On the last step running:

```
python3 convert.py
```

I got the following:

```
Traceback (most recent call last):
  File "/home/shane/projects/kittycad-play/convert.py", line 17, in <module>
    fc = create_file_conversion_with_base64_helper.sync(
  File "/home/shane/projects/kittycad-play/venv/lib/python3.10/site-packages/kittycad/api/file/create_file_conversion_with_base64_helper.py", line 25, in sync
    fc = fc_sync(
  File "/home/shane/projects/kittycad-play/venv/lib/python3.10/site-packages/kittycad/api/file/create_file_conversion.py", line 88, in sync
    return sync_detailed(
  File "/home/shane/projects/kittycad-play/venv/lib/python3.10/site-packages/kittycad/api/file/create_file_conversion.py", line 74, in sync_detailed
    return _build_response(response=response)
  File "/home/shane/projects/kittycad-play/venv/lib/python3.10/site-packages/kittycad/api/file/create_file_conversion.py", line 51, in _build_response
    parsed=_parse_response(response=response),
  File "/home/shane/projects/kittycad-play/venv/lib/python3.10/site-packages/kittycad/api/file/create_file_conversion.py", line 35, in _parse_response
    response_201 = FileConversion.from_dict(response.json())
  File "/home/shane/projects/kittycad-play/venv/lib/python3.10/site-packages/kittycad/models/file_conversion.py", line 137, in from_dict
    status = ApiCallStatus(_status)
  File "/home/shane/anaconda3/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/home/shane/anaconda3/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'completed' is not a valid ApiCallStatus
```

I'm running Pop_OS! 22.04.

I also found a broken link on the onboarding page. The last link at the bottom "Found a typo?" goes to https://github.com/KittyCAD/documentation/edit/main/_pages/docs/tutorials/onboarding.mdx and is a 404.

**Comment by jgomez720** [comment]
Thanks for finding @thesurlydev. I'll take a look this weekend.

**Comment by jgomez720** [comment]
Hey @thesurlydev, sorry for the pretty late update. We updated all the tutorial code and made sure that it's tested. This should work without problems now. If it gives you any issues, please reach out to me directly either through email (josh@zoo.dev) or through discord.
